version: '3'

services:

  db:
    image: mysql:5.7
    environment:
      - TZ=Europe/Stockholm 
      - MYSQL_ROOT_PASSWORD=password12
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak 
#    env_file: ./env/.envmysql
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_accounts:/var/lib/mysql
   
  sso:
    image: dina/keycloak:v0.1
    environment:
      - TZ=Europe/Stockholm
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=keycloak
      - MYSQL_USERNAME=keycloak
      - MYSQL_PASSWORD=keycloak 
  #  env_file: ./env/.envmysql
    ports:
      - "8080:8080"
    links:
      - db:mysql 
 
  api:
    image: dina/accounts-api:v0.1
    ports:
      - "8181:8181"
  #  links:
  #    - db:mysql

  ui:
    image: dina/accounts-ui:v0.1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.template
    environment:
      - VIRTUAL_HOST=beta-accounts.dina-web.net
      - VIRTUAL_PROTO=http
      - NGINX_HOST=beta-accounts.dina-web.net
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$NGINX_ROOT $$NGINX_INDEX' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  db_accounts:
